### ISSUE TITLE
Check this out

### ISSUE THREAD

**Issue by JJ** [JJ/literaturame#1]
I have checked out IWANN and it admits papers on self-organizing stuff. This has not been published so far except as technical report. i have added you two to the ResearchGate project. 
it's written in RMarkdown, it would have to be converted to Latex and then put in the LNCS format. I can do the initial conversion, but adaptation, checking stuff, converting to LNCS and adding maybe some other paper-y things would have to be done by you. @amorag @pacastillo.

**Comment by amorag** [comment]
Ok ;)

**Comment by pacastillo** [comment]
Great!!!

**Comment by JJ** [comment]
Please accept the invitation to the repository.
