### ISSUE TITLE
Pink noise

### ISSUE THREAD

**Issue by ccottap** [JJ/literaturame#14]
Some clarification on the analysis of the power spectrum should be included. The data shown is a linear loglog fit of coefficients found by fft, or a loglog fit of the square of these coefficients? The power carried by a certain frequency is proportional to the square of its amplitude, so it should be the latter. I suspect the fit shown is to raw coefficients, which would be consistent with the fact that the resulting slopes tend to be around -0.5.

**Comment by JJ** [comment]
I'll check this out. The fitting code is in the paper itself, from line 624:

        spec.fit <- lm(log(this.spectrum$spec) ~ log(this.spectrum$freq))

So it's a loglog fit of coefficients. I'll try to do it with squares. Which is actually just 2*log, right?

**Comment by ccottap** [comment]
Something odd going on here. The coefficients had not changed so I took a look at the code and saw something misplaced: the fit should be to the log of the aquare, rather than to the square of the log, thus: 
    spec.fit <- lm(log(this.spectrum$spec) ~ log(this.spectrum$freq^2))
Now, this may be a trivial issue but it is evading me: by doing so, the coefficients are actually halved rather than doubled. I do not know R enough to debug this.

**Comment by JJ** [comment]
I already did that:

     spec.fit <- lm(log(this.spectrum$spec) ~ log((this.spectrum$freq))**2)

It's actually the same. What is being fit is to the left of the `~` so it's natural that it goes that way, no big deal.

**Comment by ccottap** [comment]
`log((this.spectrum$freq))**2` is the square of the log, and it should be the log of the square: `log((this.spectrum$freq)**2)`. But there is another issue: check the coefficients of the raw log-log fit and those of the log-log(square) fit. The latter should be twice the former, but it is not the case (unless there is a problem on my side when compiling the document).

**Comment by JJ** [comment]
OK, will look into that.
