### ISSUE TITLE
Add fitting lines for Zipf

### ISSUE THREAD

**Issue by JJ** [JJ/literaturame#9]
In figure 3. Improve or maybe eliminate labels. They are just useless.

**Comment by pacastillo** [comment]
When compiling the .Rnw file, I can not obtain the figures 1, 4, 5, and table 4.

Figure 3 and tables 1, 2, 3 are created (and shown) properly.

**Comment by JJ** [comment]
Did you check all needed modules are installed?

**Comment by JJ** [comment]
Not going to do this.
